version: '2.28'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:7.4.0
    container_name: detemiro-api-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.12.0-management
    container_name: detemiro-api-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  action-manager-api:
    container_name: detemiro-api-action-manager-api
    build:
      context: '.'
      dockerfile: apps/action-manager/Dockerfile
      args:
        APP_MODE: api
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      APP__NAME: detemiro-api-action-manager-api
      APP__PORT: 3000
      DATABASE__URL: postgres://postgres:postgres@postgres:5432/postgres?schema=public
      REDIS__HOST: redis
      REDIS__PORT: 6379
      RABBIT__URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      RABBIT__QUEUE: detemiro-api-listener

  action-manager-worker:
    container_name: detemiro-api-action-manager-worker
    build:
      context: '.'
      dockerfile: apps/action-manager/Dockerfile
      args:
        APP_MODE: worker
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      NODE_ENV: development
      APP__NAME: detemiro-api-action-manager-worker
      DATABASE__URL: postgres://postgres:postgres@postgres:5432/postgres?schema=public
      REDIS__HOST: redis
      REDIS__PORT: 6379
      RABBIT__URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      RABBIT__QUEUE: detemiro-api-listener

volumes:
  db-data:
  redis-data:
